// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpeEkaJeAx2SAN-_cQpY3DT-e5p4hBYs',
    appId: '1:220931451245:web:a10189b8d91f4631ae9264',
    messagingSenderId: '220931451245',
    projectId: 'social-network-app-d5d06',
    authDomain: 'social-network-app-d5d06.firebaseapp.com',
    storageBucket: 'social-network-app-d5d06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyfCu0jIZywhK1Z3T9BHD4w_THoDFt8E',
    appId: '1:220931451245:android:afb6d4461b05e3acae9264',
    messagingSenderId: '220931451245',
    projectId: 'social-network-app-d5d06',
    storageBucket: 'social-network-app-d5d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRBIokXulLlBdpjFCbhXg6yDrC00w3qw',
    appId: '1:220931451245:ios:d7f0f9d985e4aa98ae9264',
    messagingSenderId: '220931451245',
    projectId: 'social-network-app-d5d06',
    storageBucket: 'social-network-app-d5d06.appspot.com',
    iosClientId: '220931451245-d45m9b8cckfi7it6g2s0749fa4p2upa0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
